name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: git-for-windows/setup-git-for-windows-sdk@v1
      with:
        flavor: build-installers # this includes all the required tools
    - name: restrict PATH to Git for Windows' SDK (and Windows)
      shell: bash
      run: echo 'PATH=/mingw64/bin:/usr/bin/:/c/Windows/system32' >>$GITHUB_ENV
    - name: mingw64_defconfig
      shell: bash
      run: |
        # We do not _actually_ cross-compile
        sed -i 's/^\(CONFIG_CROSS_COMPILER_PREFIX=\).*/\1""/' configs/mingw*

        make -j$(nproc) mingw64_defconfig
    - name: build busybox.exe
      shell: bash
      run: make -j$(nproc) busybox.exe
    - name: upload busybox artifact
      uses: actions/upload-artifact@v2
      with:
        name: busybox
        path: busybox.exe
    - name: install test dependencies
      shell: bash
      run: pacman -Sy --noconfirm sharutils xz zip
    - name: run testsuite
      shell: bash
      working-directory: ./testsuite
      run: ../busybox.exe sh ./runtest -v
      env:
        DEBUG: true
        LC_ALL: C
        SKIP_KNOWN_BUGS: true
        TZ: UTC
